#!/bin/bash

echo -e "Checking code with flake8\c"
# E501 Line too long
# W293 Blank line contains whitespace
# N806 Variable in function should be lowercase (we use Pylint for naming conventions)
# E124 Closing bracket does not match visual indentation (we use Pylint for brackets)
# N803 Argument name should be lowercase
flake_result=$(flake8 \
    --ignore=E501,W293,N806,E124,N803 \
    src tests)
flake_status=$?

if [ $flake_status -eq 0 ]
then
    echo -e " \033[34m(success)\033[0m"
else
    echo -e " \033[33m(failure)\033[0m"
fi

echo -e "Checking code with pylint\c"
# --good-names => whitelist of variables
# -rn => 
# -iy => include msgids
# -d ... => disable msgs
# C0111 documentation
# R0904 Too many public methods (46/20)
# R0922 Abstract class is only referenced 1 times
# W0511 TODO's
# W0403 Relative import 'TimeoutThread', should be 'src.TimeoutThread'
# R0801 Similar lines in 2 files
# I0011 Locally disabling C0103
# W0105 String statement has no effect (block comments in Python)
# W0107 Unnecessary pass statement
# W0613 Unused argument 'X'
# R0201 Method could be a function (i.e. does not use self)
# R0914 Too many local variables (16/15)
# C0301 Line too long
# E0602 Undefined variable
# E1101 No-Member
# E1103 Maybe-No-Member
# R0912 Too-many-branches

pylint_result=$(PYTHONPATH=$PYTHONPATH:.:./src pylint \
    --good-names=x,y,X,Y,e,i,j \
    -rn \
    '--msg-template={path}:{line}: [{msg_id}({symbol}), {obj}] {msg}' \
    '-dC0111,R0904,R0922,W0511,W0403,R0801,I0011,W0105,W0107,W0613,R0201,R0914,C0301,E1101,E1103,E0602,C0303,R0912' \
    --module-rgx="(([a-z_][a-z0-9_]*)|([A-Z][a-zA-Z0-9]+)|(test_[a-zA-Z0-9]+)|(setUp)|(setUpClass)|(tearDown))$" \
    --variable-rgx="(([a-z_][a-zA-Z0-9_]*)|(TPTPPath))$" \
    --dummy-variables-rgx="(_[a-z][a-zA-Z0-9]*)" \
    src tests)
pylint_status=$?

if [ $pylint_status -eq 0 ]
then
    echo -e " \033[34m(success)\033[0m"
else
    echo -e " \033[33m(failure)\033[0m"
fi

if [ $flake_status -eq 0 ] && [ $pylint_status -eq 0 ]
then
    echo -e "\033[32mCode was good, you can commit this.\033[0m"
    exit 0
else
    echo "$flake_result"
    echo "$pylint_result"
    echo -e "\033[31mCode was not conformant. If you really want to commit, you can use --no-verify.\033[0m"
    exit 1
fi
